export const CHANGE_CHECKBOX='CHANGE_CHECKBOX';
export const CHANGE_TABS='CHANGE_TABS';
export const FETCH_TICKETS='FETCH_TICKETS';
export const FETCH_URL_ID='FETCH_URL_ID';
export const TICKETS_LOADED='TICKETS_LOADED';
export const FETCH_ERROR='FETCH_ERROR';
export const UPDATE_TICKETS='UPDATE_TICKETS';